version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: evaexchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/evaexchange
      - PORT=3000
    ports:
      - "3000:3000"
